myapp/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.landing_view, name="landingPage"),
    path('pricing', views.pricing_view, name="pricingPage"),
    path('contact', views.contact_view, name="contactPage"),
    path('register', views.register_view, name="registerPage"),
    path('login', views.login_view, name="loginPage"),
    path('dashboard', views.dashboard_view, name="dashboardPage"),
    path('logout', views.logout_view, name="logoutPage"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]

myapp/models.py
from django.db import models

# Create your models here.
class ContactModel(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message = models.TextField()

class TaskBoard(models.Model):
    taskName = models.CharField(max_length=100)
    endDate = models.DateField()
    
    

    

myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from .models import ContactModel

class RegisterForm(forms.ModelForm):
    username = forms.CharField(label="username",max_length=100,required=True)
    email = forms.EmailField(label="email",max_length=100,required=True)
    password = forms.CharField(label="password",max_length=100,required=True)
    confirm_password = forms.CharField(label="confirm_password",max_length=100,required=True)

    class Meta:
        model = User 
        fields = ['username','email','password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError('Password mismatch')

class ContactForm(forms.ModelForm):
    username = forms.CharField(max_length=100,required=True)
    email = forms.EmailField(max_length=100,required=True)
    message = forms.CharField(required=True)

    class Meta:
        model = ContactModel
        fields = ['username','email','message']

class LoginForm(forms.Form):
    username = forms.CharField(label="username",max_length=100,required=True)
    password = forms.CharField(label="password",max_length=100,required=True)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username,password=password)
            if user is None:
                raise forms.ValidationError("Invalid Username/Password")


myapp/views.py
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from django.contrib import messages
from .forms import ContactForm, LoginForm, RegisterForm
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

# Create your views here.
def landing_view(request):
    return render(request, "landingPage.html")

def pricing_view(request):
    return render(request,'pricingPage.html')

def contact_view(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']

        if form.is_valid():
            form.save()
            messages.success(request,'Your response is recorded')
            # return render(request,'contactPage.html')
    return render(request, 'contactPage.html')

def register_view(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        username = request.POST.get('username')
        email = request.POST.get('email')
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            messages.success(request,'You have successfully created an account',{'username':username,'email':email})
            return redirect('app:loginPage')
        return render(request,'registerPage.html',{'form':form})
    return render(request,'registerPage.html')

def login_view(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username,password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('app:dashboardPage')
    return render(request, 'loginPage.html',{'form':form})

def dashboard_view(request):
    return render(request, 'dashBoard.html')

def logout_view(request):
    auth_logout(request)
    return redirect('app:loginPage')


myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link href="./style.css" rel="stylesheet" />

    <title>Document</title>
</head>

<body class="container">

    <!-- Nav -->
    {% include "includes/nav.html" %}

    <!-- Dynamic content -->
    {% block content %}
    {% endblock  %}

    <!--Footer -->
    {% include "includes/footer.html" %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>

</html>

myapp/templates/contactPage.html
{% extends "base.html" %}

{% block content %}
    <div class="position-absolute top-50 start-50 translate-middle">
        <!-- Field errors -->
        {% include "includes/errors.html" %}
        <h1>Contact Form</h1>
        <form class="form" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-6 my-3">
                    <input class="form-control" name="username" type="text" placeholder="Username" />
                </div>
                <div class="col-6 my-3">
                    <input class="form-control" name="email" type="email" placeholder="Email" />
                </div>
                <div class="col-12 my-3">
                    <textarea class="form-control" name="message" rows="6" placeholder="Message"></textarea>
                </div>
                <center>
                    <button type="sumbit" class="btn btn-success px-5">Send</button>
                </center>
            </div>
        </form>
        
    </div>
{% endblock %}

myapp/templates/dashBoard.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        {% include "includes/sidePanel.html" %}
        <main class="col-10">
            <h1>Dashboard</h1>
        </main>
    </div>
{% endblock content %}

myapp/templates/includes/errors.html
{% for field in form %}
    {% for error in field.errors %} 
        <div class="alert alert-danger">
            {{field.name|title}}: {{error}} 
        </div>
    {% endfor %}
{% endfor %} 

{% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        {{error}}
    </div>
{% endfor %} 

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">
            {{message}}
        </div>
    {% endfor %}
{% endif %}

myapp/templates/includes/footer.html
<footer class="footer fixed-bottom mb-0">
    <p class="text-muted text-center">&copy; All rights reserved</p>
</footer>

myapp/templates/includes/nav.html
<nav class="navbar">
    <a class="navbar-brand" href="{% url "app:landingPage" %}">Home</a>
    <div class="nav">
        <a href="{% url "app:pricingPage" %}" class="nav-link">Pricing</a>
        <a href="{% url "app:contactPage" %}" class="nav-link">Contact</a>
        
        {% if user.is_authenticated %}
        <a href="{% url "app:dashboardPage" %}" class="nav-link">Dashboard</a>
        <a href="{% url "app:logoutPage" %}" class="nav-link">Logout</a>
        {% else %}
        <a href="{% url "app:registerPage" %}" class="nav-link">Register</a>
        <a href="{% url "app:loginPage" %}" class="nav-link">Login</a>
        {% endif %}
    </div>
</nav>

myapp/templates/includes/sidePanel.html
<div  class="col-2" style="height:100vh; background-color:#4F0341">
    <p class="text-light fw-bold navbar-brand px-3">Hi [Username]</p>
    <div>
        <a class="nav-link text-decoration-none text-light" href="#">All post</a>
        <a class="nav-link text-decoration-none text-light" href="#">Add post</a>
        <a class="nav-link text-decoration-none text-light" href="#">Today Task</a>
        <a class="nav-link text-decoration-none text-light" href="#">Filters</a>
        <a class="nav-link text-decoration-none text-light" href="#">Activity Log</a>
        <a class="nav-link text-decoration-none text-light" href="#">Sign Out</a>
    </div>
</div>

myapp/templates/landingPage.html
{% extends "base.html" %}

{% block content %}
    <div class="d-flex bd-highlight">
        <div class="align-self-center">
            <h1>Task Scheduler</h1>
            <p class="text-muted">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis illo suscipit
                id esse iure! Neque animi nostrum vero! Recusandae eligendi a dolores possimus repellendus autem
                libero soluta alias sed maxime.</p>
        </div>
        <div class="p-2 bd-highlight">
            <img src="https://i.pinimg.com/736x/09/da/96/09da96ca14b546b26ad8297557bcb5b8.jpg" alt="image" />
        </div>
    </div>
{% endblock %}

myapp/templates/loginPage.html
{% extends "base.html" %}
{% block content %}
    <div class="shadow-lg border border-warning rounded-3 p-3 position-absolute top-50 start-50 translate-middle" style="min-width: 23%;min-height:40%">
        {% include "includes/errors.html" %}
        <h1 class="text-center mb-5" style="font-family:Verdana;">Sign In</h1>
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                <input class="form-control mb-4" name="username" value="{{form.username.value|default:''}}" type="text" placeholder="Username" />
                <input class="form-control mb-4" name="password" type="password" placeholder="Password" />
                <div class="d-grid gap-2 col-4 mx-auto">
                    <button class="btn btn-success" type="submit">Log in</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

myapp/templates/pricingPage.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h5 class="text-muted text-center">Pricing</h5>
        <h1 class="text-center">Easily organize your work. Start free.</h1>
        <h5 class="text-muted text-center">Access our features. No credit card required.</h5>
    
        <div class="row d-flex justify-content-center">
                <div class="col-3 m-3 card">
                    <div class="card-header">
                        <h5>Personal</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-title">For individuals and small teams looking to manage their tasks.</p>
                        <p class="card-text"><span class="fw-bold">US$0</span> <br /> Free forever</p>
                        <a href="#" class="btn btn-primary mb-2">Get started</a>
        
                        <p class="card-text">Manage task and personal to-dos:</p>
                        <ul>
                            <li>Unlimited tasks</li>
                            <li>Unlimited tasks</li>
                            <li>Basic search filters</li>
                            <li>List view projects</li>
                        </ul>
                    </div>
                </div>
        
                <div class="col-3 m-3 card">
                    <div class="card-header">
                        <h5>Starter</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-title">For growing teams that need to track their projects' progress and hit deadlines.</p>
                        <p class="card-text"><span class="fw-bold">US$6.92</span> <strike class="text-muted">US$10.99</strike></p>
                        <a href="#" class="btn btn-primary mb-2">Get started</a>
        
                        <p class="card-text">Manage task and personal to-dos:</p>
                        <ul>
                            <li>Unlimited tasks</li>
                            <li>Unlimited tasks</li>
                            <li>Basic search filters</li>
                            <li>List view projects</li>
                        </ul>
                    </div>
                </div>
        
                <div class="col-3 m-3 card">
                    <div class="card-header">
                        <h5>Advanced</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-title">For companies that need to manage a portfolio of work and goals across departments.</p>
                        <p class="card-text"><span class="fw-bold">US$15.74</span> <strike class="text-muted">US$24.99</strike></p>
                        <a href="#" class="btn btn-primary mb-2">Get started</a>
        
                        <p class="card-text">Manage task and personal to-dos:</p>
                        <ul>
                            <li>Unlimited tasks</li>
                            <li>Unlimited tasks</li>
                            <li>Basic search filters</li>
                            <li>List view projects</li>
                        </ul>
                    </div>
                </div>
        </div>
    </div>
{% endblock  %}
    

myapp/templates/registerPage.html
{% extends "base.html" %}
{% block content %}
    <div class="shadow-lg border border-warning rounded-3 p-3 position-absolute top-50 start-50 translate-middle" style="min-width: 23%;min-height:60%">
        {% include "includes/errors.html" %}
        <h1 class="text-center my-4" style="font-family:Verdana;">Sign Up</h1>
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                
                <input class="form-control mb-4" name="username" value="{{username}}" type="text" placeholder="Username" />
                <input class="form-control mb-4" name="email" value="{{email}}" type="email" placeholder="Email" />
                <input class="form-control mb-4" name="password" type="password" placeholder="Password" />
                <input class="form-control mb-4" name="confirm_password" type="password" placeholder="Confirm Password" />
                <div class="d-grid gap-2 col-4 mx-auto">
                    <button class="btn btn-success" type="submit">Register</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}